#+TITLE: Laboratorul de Criptografie
#+AUTHOR: Adrian Manea

* Scop
În acest repository veți găsi cea mai mare parte a materialelor pentru
laboratorul de criptografie. Restul materialelor se găsesc la secțiunea
corespunzătoare de pe [[https://adrianmanea.xyz/pages/4-didactica.php][site-ul meu personal]].

* Organizare
În general, organizarea se va face în foldere diferite pentru fiecare
laborator, eventual cu adăugarea suplimentelor atunci cînd este necesar.
De exemplu, folderul =lab1= din directorul curent va conține materialele
aferente primului laborator. Aceste materiale vor conține noțiuni teoretice,
exerciții rezolvate, exerciții propuse, teme rezolvate și orice alte
materiale se vor considera utile.

Studenții participanți vor fi adăugați la repository cu drepturi depline,
vor putea citi, descărca materiale și încărca teme sau alte materiale ori
propuneri pentru buna desfășurare a seminarului.

Corectarea temelor, sugestii, comentarii și orice fel de feedback se vor
transmite fie prin secțiunea [[https://github.com/adimanea/fsa-lab-cripto/issues][Issues]] (preferabil), fie prin email.
