#+TITLE: Laborator 2: Aritmetică și numere speciale
#+AUTHOR: Adrian Manea

* Recapitulare: Inverse modulare
*Exercițiu L2.1* Scrieți un program care să rezolve ecuația ~a*x + b = c~
modulo ~n~, unde ~a, b, c, n~ sînt citite de la tastatură, iar ~x~ este
soluția care trebuie afișată.

*Atenție:* Există posibilitatea ca ecuația să nu aibă soluție! În ce caz?


--------------------------------------------------------



Majoritatea algoritmilor criptografici se bazează pe numere prime și pe
numere cu anumite proprietăți speciale, într-un anume sens. În acest
laborator, vom inventaria cîteva tipuri de astfel de numere și vom scrie
programe simple care să le găsească și să le prelucreze.

* Fracții ireductibile
Dacă ~a/b~ este o fracție de numere întregi, ea poate fi făcută ireductibilă
simplificînd cu ~cmmdc(a,b)~.

*Exercițiu L2.2* Citiți de la tastatură ~a~ și ~b~, afișați ~cmmdc(a,b)~ și fracția ireductibilă rezultată.

Exemplu:
#+begin_example
a = 1524096
b = 9072000
cmmdc(a,b) = 72576
ireductibil: 21/125
#+end_example

* cmmdc pentru ~n~ numere
Se poate defini cmmdc pentru ~n~ numere inductiv, astfel. Presupunem că avem
~n~ numere naturale, ~a[1], a[2], a[3], ..., a[n]~. Atunci
~cmmdc(a[1], a[2], ..., a[n]) = cmmdc(cmmdc(a[1], a[2], ..., a[n-1]), a[n])~.

*Exercițiu L2.3* Folosind acest rezultat și o funcție care calculează ~cmmdc~ pentru 2 numere naturale,
citiți de la tastatură ~n~, apoi ~n~ numere naturale și afișați-le ~cmmdc~.

* Adunarea fracțiilor
*Exercițiu L2.4* Citiți de la tastatură un număr natural ~n~, care este numărul de fracții, 
apoi ~2*n~ numere naturale, care reprezintă perechi (numărător, numitor) pentru cele ~n~ fracții.

Aduceți-le la același numitor și calculați suma fracțiilor.

*Atenție:* 

1. Avem nevoie de condiții de validare, nu orice fracție poate fi acceptată!

2. Putem considera mai întîi cazul cînd lucrăm doar cu numere pozitive. Modificați programul încît să meargă și pentru numere negative.

* Factorizare
*Exercițiu L2.5* Se citește de la tastatură un număr natural ~n~, de maximum 10 cifre. Să se afișeze descompunerea lui în factori primi.
Exemplu: ~n = 1000, output = 2^3 * 5^3~.

* Conjectura lui Collatz
Acest rezultat, nedemonstrat încă, afirmă că, dacă se pornește cu un întreg
=n=, se poate ajunge mereu la =1=, aplicînd numai pașii de mai jos:
- dacă numărul curent este par, se înjumătățește;
- dacă numărul curent este impar, se înmulțește cu 3 și se adaugă 1.

Exemplu: ~10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1~.

*Exerciții*

L2.6. Scrieți un program care să verifice această conjectură pentru un număr citit de la tastatură, afișînd toți pașii intermediari, precum și numărul total al pașilor.

L2.7. Scrieți un program care găsește numărul mai mic decît 10,000,000 care necesită cei mai mulți pași pentru a ajunge la 1.

* Constanta lui Kaprekar
Folosim următoarele reguli:
1. Se ia orice număr natural de 4 cifre, cu oricare două cifre diferite;
2. Se ordonează cifrele crescător și descrescător;
3. Se scade numărul mai mic din cel mai mare;
4. Se repetă procedura cu rezultatul obținut.

După maximum 7 pași, se va ajunge la același rezultat, 6174, numit și /constanta lui Kaprekar/.

*Atenție:* Sînt permise și numere cu zerouri, de exemplu, dacă se alege numărul 3021 la
început, cel mai mare număr obținut din el este 3210, iar cel mai mic, 0123 = 123.

Exemplu: pentru 3524 obținem:

#+begin_example
    5432 – 2345 = 3087
    8730 – 0378 = 8352
    8532 – 2358 = 6174
    7641 – 1467 = 6174
#+end_example

*Exerciții*

L2.8 Scrieți un program care să aplice pașii de mai sus, arătînd de fiecare dată pașii intermediari.

L2.9 Procedura funcționează și pentru numere de 3 cifre, finalizîndu-se cu 495, în maximum 6 pași. Scrieți un program și pentru acest caz.

* Indicatorul lui Euler
Pentru orice număr natural ~n~, se definește ~phi(n)~ ca fiind numărul de numere naturale,
mai mici sau egale cu ~n~, coprime cu ~n~. Altfel spus, ~phi~ numără cîte numere mai mici
decît ~n~ au cmmdc 1 cu ~n~.

Exemplu: ~phi(10) = 4~, deoarece 10 este coprim cu 1, 3, 7, 9.

*Exercițiu L2.10.* Scrieți un program care calculează ~phi(n)~, pentru ~n~ citit de la tastatură.
Afișați și numerele coprime cu ~n~.

* Mica teoremă lui Fermat și formula lui Euler
*Fermat:* Pentru orice număr natural ~a~, are loc ~a^p = a (mod p)~.

*Euler:* Pentru orice număr natural ~a~, are loc ~a^phi(n) = 1 (mod n)~.

*Exercițiu L2.11.* Scrieți cîte un program care să verifice cele două teoreme, pentru
~a, n, p~ citite de la tastatură.

Exemplu: ~a = 3, p = 5, n = 10~. Output:
#+begin_example
3^5 = 243 = 3 mod 5

phi(10) = 4
3^4 = 81 = 1 mod 10
#+end_example

* Număr divizibil cu toate numerele naturale
*Exercițiu L2.12.*

Cel mai mic număr care se divide cu toate numerele de la 1 la 10 este 2520.
Aflați cel mai mic număr care se divide cu toate numerele de la 1 la 20.

* Numere triunghiulare cu mulți divizori
Un număr se numește /triunghiular/ dacă poate fi obținut ca suma primelor
numere naturale. Astfel, al ~n~-lea număr triunghiular este 1 + 2 + 3 + ... + n.

*Exercițiu L2.13.* Care este cel mai mic număr triunghiular care are 100 divizori?


